name: verde_ensina
description: "Verde Ensina Pro"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Router (padrão profissional)
  go_router: ^14.0.0

  # --- Adicionados e Corrigidos ---
  # A versão do intl foi atualizada para evitar o conflito com o flutter_localizations
  intl: ^0.20.2        
  
  # Geolocalização e API
  geolocator: ^13.0.1  
  http: ^1.2.2         

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true